[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about-vikram-bahl"
  weight = -109

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/svram"
#[[social]]
  #name = "twitter"
  #weight = 2
  #url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 2
  url = "https://www.linkedin.com/in/vikram-bahl-0668bb1b/"
#[[social]]
  #name = "rss"
  #weight = 4
  #url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"